---
title: "Notes"
author: "Jinliang Yang"
date: "July 23, 2015"
output: html_document
---

# GBS data Summary

## loading HDF5 raw data
 - loading in genotypes from HDF5 file `largedata/teo.h5`
 - filtering biallelic loci: Removed `357,647` loci non-biallelic.
 - [1:598043, 1:4875]

```{r}
info <- read.csv("../data/teo_info.csv")
imiss <- read.csv("../data/teo_imiss.csv")

par(mfrow=c(1,2))
hist(imiss$imiss, main="per plant (N=4,875)", col="#008080", breaks=100, xlab="missing rate")
abline(v=0.8, col="red", lty=2, lwd=3)
hist(info$lmiss, main="per locus (N=598,043)", col="#008080", breaks=100, xlab="missing rate")
abline(v=0.8, col="red", lty=2, lwd=3)
```


```{r, eval=TRUE}
par(mfrow=c(1,2))
hist(info$maf, main="Minor Allele Freq (N=598,043)", col="#008080", breaks=100, xlab="MAF")
abline(v=0.8, col="red", lty=2, lwd=3)

hist(subset(info, maf>0.01)$maf, main="MAF >0.01 (N=401,352)", col="#008080", breaks=100, xlab="MAF")
abline(v=0.8, col="red", lty=2, lwd=3)
```

# Parentage Infomation



```{r}
pinfo <- read.table("../data/parentage_sum.txt", header=TRUE)
dim(pinfo)
subset(pinfo, !is.na(WGS))
subset(pinfo, nox < 30)

```


# Comparing GBS vs. WGS




----------

```{r}

par(mfrow=c(1,2)) 
hist(lmiss1, main="WGS (N=301,249)", ylim=c(0, 70000), col="#008080", breaks=50, xlab="missing rate")
#abline(v=0.8, col="red", lty=2, lwd=3)
hist(lmiss2, main="GBS (N=301,249)", ylim=c(0, 70000), col="#008080", breaks=50, xlab="missing rate")
#abline(v=0.8, col="red", lty=2, lwd=3)

par(mfrow=c(1,2)) 
hist(imiss1, main="WGS (N=19)",  col="#008080",  xlab="missing rate")
#abline(v=0.8, col="red", lty=2, lwd=3)
hist(imiss2, main="GBS (N=19)",  col="#008080",  xlab="missing rate")
#abline(v=0.8, col="red", lty=2, lwd=3)

par(mfrow=c(1,2)) 
hist(maf1, main="WGS (N=301,249)",  col="#008080",  xlab="MAF")
#abline(v=0.8, col="red", lty=2, lwd=3)
hist(maf2, main="GBS (N=301,249)",  col="#008080",  xlab="MAF")
#abline(v=0.8, col="red", lty=2, lwd=3)

```


